import os
import sys
import json
import sqlite3
import requests
from pathlib import Path
from src.database.db_handler import DB_PATH, get_patient_timeline
from src.agents.orchestrator_agent import PatientClinicalState, PatientOrchestrator
from src.vector_db.ada_vector_store import LocalADAVectorStore

# Set up local paths
ROOT_DIR = Path(__file__).resolve().parent.parent.parent
OUTPUT_DIR = ROOT_DIR / "data" / "processed"

class OllamaEvaluator:
    def __init__(self, model_name="qwen3.5:9b", base_url="http://localhost:11434"):
        self.model_name = model_name
        self.base_url = base_url
        
    def evaluate(self, report: str) -> dict:
        prompt = f"""
You are an expert clinical RAG evaluator. 
Review the following medical report generated by an AI pipeline:

--- REPORT START ---
{report}
--- REPORT END ---

Score the report on the following two metrics, each from 1 to 5.
1. Groundedness (1-5): Does the report explicitly cite exact ADA Guidelines, specifically including [Page X] or (ID: ...) annotations for its medication recommendations? 5 means strict citations present, 1 means no citations.
2. Context Precision (1-5): Are the recommendations logically consistent with the patient's complications (e.g. eGFR and HbA1c trajectory)? 5 means perfect alignment.

Respond ONLY with a valid JSON object in this format:
{{"groundedness": 5, "context_precision": 5, "reasoning": "brief explanation"}}
"""
        try:
            response = requests.post(f"{self.base_url}/api/generate", json={
                "model": self.model_name,
                "prompt": prompt,
                "stream": False,
                "format": "json"
            }, timeout=60)
            
            if response.status_code == 200:
                data = response.json()
                return json.loads(data["response"])
            else:
                return {"error": "Failed to connect to Ollama"}
        except Exception as e:
            return {"error": str(e)}

def fetch_test_patients(limit=5):
    conn = sqlite3.connect(DB_PATH)
    try:
        rows = conn.execute(f"SELECT patient_nbr FROM dim_patients LIMIT {limit}").fetchall()
        return [r[0] for r in rows]
    finally:
        conn.close()

def main():
    print("Starting Automated RAG Evaluation Pipeline (Local Ollama)...")
    
    # 1. Fetch 5 test patients
    patient_ids = fetch_test_patients(5)
    print(f"Testing {len(patient_ids)} patients: {patient_ids}")
    
    vdb = LocalADAVectorStore()
    evaluator = OllamaEvaluator()
    
    results = []
    total_groundedness = 0
    total_context_precision = 0
    valid_evals = 0
    
    # 2. Loop through and evaluate
    for pid in patient_ids:
        print(f"\n--- Evaluating Patient {pid} ---")
        raw_record = get_patient_timeline(pid)
        state = PatientClinicalState(
            patient_nbr=pid,
            demographics=raw_record.get("demographics", {}),
            raw_timeline=raw_record.get("timeline", [])
        )
        
        # Run orchestrator
        orchestrator = PatientOrchestrator(state, vdb, use_mock_llm=True)
        report = orchestrator.run_orchestration()
        
        # Grade with Ollama
        print("Scoring report with qwen3.5:9b...")
        score = evaluator.evaluate(report)
        print(f"Score: {score}")
        
        results.append({
            "patient_nbr": pid,
            "scores": score
        })
        
        if "groundedness" in score and "context_precision" in score:
            total_groundedness += int(score["groundedness"])
            total_context_precision += int(score["context_precision"])
            valid_evals += 1
            
    # 3. Save and summarize
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / "eval_results.json"
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
        
    print("\n==================================")
    print("EVALUATION COMPLETE")
    if valid_evals > 0:
        print(f"Average Groundedness: {total_groundedness/valid_evals:.1f} / 5.0")
        print(f"Average Context Precision: {total_context_precision/valid_evals:.1f} / 5.0")
    print(f"Results saved to {out_path}")
    print("==================================")

if __name__ == "__main__":
    main()
